### ISSUE TITLE
Stop making all constants private

### ISSUE THREAD

**Issue by adrianna-chang-shopify** [Shopify/maintenance_tasks#314]
Rafael mentioned that we should not prevent people from extending our classes if they are willing to accept the risks involved. 

A recent example involved a team needing to patch the gem's `ApplicationController` in order to specify a `before_action` callback that would provide user authorization.

We should remove the `private_constant` declarations on our classes and the corresponding [test](https://github.com/Shopify/maintenance_tasks/blob/main/test/lib/maintenance_tasks_test.rb).

**Comment by etiennebarrie** [comment]
We don't really prevent people from extending the classes though, they can still do it, it's just more clear they're doing something that is not supported and that can break easily.

I'm all for supporting specific uses cases, for example regarding the authorization, I think if hooking ApplicationController is what's needed, we could definitely make it public, and maybe point out to people in the README what they can do.

Or maybe it's too high level, if making decisions based on `controller_name` and `action_name` isn't ideal (that's what's going to happen if you hook into ApplicationController), we could implement some kinds of hooks specific to what's needed in that use case (authorization on starting/pausing/cancelling a run). Because even if you prevent starting a run with a controller hook, the button would still be there, which isn't great.

**Comment by adrianna-chang-shopify** [comment]
> I'm all for supporting specific uses cases

Agree 100% that if there is an obvious use case then users should be able to use a documented, public API to implement what they need. Auth is a good example, we had talked about building that right into the gem, but exposing ApplicationController and providing documentation on how to patch it to set filters for authentication is good enough.

> We don't really prevent people from extending the classes though, they can still do it, it's just more clear they're doing something that is not supported and that can break easily.

Right, but they have to use `const_get` which is a pain. @rafaelfranca had mentioned
> It is always better to allow people to extend classes if they are willing to accept the risks

I was wondering if we could rely entirely on `@api private` to denote parts of the library that shouldn't be extended as it's risky, but interestingly YARD actually says [this](https://rubydoc.info/gems/yard/file/docs/Tags.md#private) about the private tag:
> This tag should only be used to mark objects private when Ruby visibility rules cannot do so. In Ruby 1.9.3, you can use private_constant to declare constants (like classes or modules) as private, and should be used instead of @api private

So 🤷‍♀️  Maybe we just need to be more open to making things in the gem public if users come forward with potential use cases where they'd like to extend

**Comment by etiennebarrie** [comment]
`@api private` is not the same as `@private`. `@private` is what you quoted, it hides or marks as private a constant or method, whereas `@api private` adds the big yellow notice.

https://rubydoc.info/gems/yard/file/docs/Tags.md#api

So I think yes we could rely on just the `@api private` for private constants, but it's a bit like saying there's no point in using private methods, and we could just use public methods for everything, because using `send` is too much of a pain.

**Comment by adrianna-chang-shopify** [comment]
My bad, I should read things more carefully 🤦‍♀️ Yeah so `@api private` is what we would want to use. 

>it's a bit like saying there's no point in using private methods, and we could just use public methods for everything, because using send is too much of a pain.

Haha that's fair, although at least with using `@api private` we're still making it clear that it's potentially risky to extend those constants, we're just reducing the friction if they actually _were_ going to overwrite one.

**Comment by adrianna-chang-shopify** [comment]
Closed by https://github.com/Shopify/maintenance_tasks/pull/344
