### ISSUE TITLE
Tasks with `csv_collection` tries to connect to the database when loaded

### ISSUE THREAD

**Issue by rafaelfranca** [Shopify/maintenance_tasks#488]
It is caused by `ActiveStorage::Attachment.table_exists?` https://github.com/Shopify/maintenance_tasks/commit/a030de8e800675964f4453a9811a43ac8a01afa8.

This is a problem because it will try to connect to the database when booting, which might fail, if for example the database was not created yet, or the database is unhealthy.

**Comment by etiennebarrie** [comment]
Good catch, I feel like we could easily guard that check against `Rails.env.production?` since it's only really helpful in development/test. I'm not a fan of doing this, but the alternative of checking whether the schema cache is used and primed seems pretty bad too. We could also just remove this but it was causing some support load.

I started looking more at whether we could test this but we can't because it seems it's not the only thing that prevents booting without a connection.

**Comment by rafaelfranca** [comment]
I found this problem in the test environment, so I don't think checking environment will help. Can't we move this check to the execution of the task instead to the definition?
