### ISSUE TITLE
Validation failed: Status Cannot transition run from status cancelled to errored

### ISSUE THREAD

**Issue by elfassy** [Shopify/maintenance_tasks#616]
Example error: https://app.bugsnag.com/shopify/banking/errors/6260400a95d9870009401416?event_id=6260400a0093682418dc0000&i=sk&m=nw

```
gems/maintenance_tasks-1.9.0models/maintenance_tasks/run.rb:133
```

Bug seems to come from
https://github.com/Shopify/maintenance_tasks/blob/main/app/validators/maintenance_tasks/run_status_validator.rb#L10

**Comment by etiennebarrie** [comment]
> Caused By: ActiveRecord::RecordInvalid · Validation failed: Status Cannot transition run from status cancelled to running

It seems like there was a job in the queue (maybe the retry queue?), and the task was cancelled. Whenever the job got worked on, it cause that failure, which was rescued, and then that caused another failure trying to move the task to errored.

The reason could be that you force cancelled a task that wasn't really failed, the job still existed in the queue. Can you confirm that's probable?

Initially we were very strict with the status validation errors as a way for us to make sure we weren't ignoring issues. Maybe we could do an exception for cancelled -> running since we have the force cancelling feature which will cause this.
