### ISSUE TITLE
Class loader Issue MaintenanceTasks::CsvCollectionBuilder

### ISSUE THREAD

**Issue by orbanbotond** [Shopify/maintenance_tasks#642]
As I turn on the eager loader and start the rails console I receive this error:

```
be rails c             7s arm64 2.7.3p183
/Users/orbanbotond/.frum/versions/2.7.3/lib/ruby/gems/2.7.0/gems/maintenance_tasks-1.10.1/app/models/maintenance_tasks/batch_csv_collection_builder.rb:9:in `<module:MaintenanceTasks>': uninitialized constant MaintenanceTasks::CsvCollectionBuilder
Did you mean?  MaintenanceTasks::NoCollectionBuilder
               MaintenanceTasks::BatchCSVCollectionBuilder
               MaintenanceTasks::CSVCollectionBuilder (NameError)
```
               
This is my ruby version:

```
ruby -v                7s arm64 2.7.3p183
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [arm64-darwin20]
```

**Comment by drcapulet** [comment]
Here are some reproduction steps with rails 6.1.7, but under Zeitwerk:

```bash
rails new testapp --skip-webpack-install --skip-javascript
```

Flip `config.eager_load` to `true` in `config/environments/development.rb`.

Then edit `config/initializers/inflections.rb` to have:

```ruby
ActiveSupport::Inflector.inflections do |inflect|
  inflect.acronym 'CSV'
end
```

And finally add `gem 'maintenance_tasks'` to `Gemfile`.

When you try to launch a console, it'll crash.

This is due to the fact that Rails doesn't isolate inflections to the main application, thus requiring something like:

```ruby
Rails.autoloaders.each do |autoloader|
  autoloader.inflector.inflect(
    'batch_csv_collection_builder' => 'BatchCsvCollectionBuilder',
    'csv_collection_builder' => 'CsvCollectionBuilder',
  )
end
```

**Comment by akabiru** [comment]
Cheers @drcapulet. For anyone curious about the zeitwerk inflections mentioned in https://github.com/Shopify/maintenance_tasks/issues/642#issuecomment-1292393956

- 📖 Check out https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#customizing-inflections
- Add `bin/rails zeitwerk:check` to your CI build, this will catch any autoload errors that would otherwise show up in `eager_load` https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#manual-testing
