### ISSUE TITLE
Adding the ability to tag tasks for filtering on the index page

### ISSUE THREAD

**Issue by lawrencewong** [Shopify/maintenance_tasks#834]
Hello!

I am wondering if anyone has found themselves in a similar position as our team.

In our team's usage of maintenance tasks we found that with the additions of new tasks, and previous runs displaying raw data it made it difficult to find specific tasks.

I've put up a PR for a proposed feature addition. Would love to get some thoughts on it, or any suggestions on how to mitigate this issue.

https://github.com/Shopify/maintenance_tasks/pull/815

Thanks!

**Comment by etiennebarrie** [comment]
There's a way in Ruby to group things classes: using modules as namespaces. We properly support nesting since #809, maybe we could give a way to filter by module instead of adding the concept of tag?
For example, `/maintenance_tasks/` could continue showing all tasks as it does today, but for projects using modules nested under `Maintenance`, we could list their names at the top of the index, allowing to filter tasks by module.

**Comment by lawrencewong** [comment]
That would be definitely preferred. We did notice that it was nice that we could have the nested structure, but saw no benefit to it since it didn't help with the ability to filter. I can take a look at making some changes in my PR to reflect that.
